ukf_filter_node_diff:
    ros__parameters:
        frequency: 50.0
        use_sim_time: true
        two_d_mode: true
        publish_acceleration: false
        predict_to_current_time: false
        publish_tf: true
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom
        map_frame: map
        sensor_timeout: 0.02

        odom0: /diff_cont/odom
        odom0_config: [false,  false,  false,     # x, y, z
               false, false, false,      # roll, pitch, yaw
               true,  false, false,     # vx
               false, false, false,     # vy, vz
               false, false, false]     # wx, wy, wz


        imu0: /imu_cov
        imu0_config: [false, false, false,
                      false,  false,  true,
                      false, false, false,
                      false, false, false,
                      false, false, false]

        imu0_queue_size: 3
        imu0_differential: false
        imu0_remove_gravitational_acceleration: false

